### ISSUE TITLE
nerdctl unable to resolve image to copy --from 

### ISSUE THREAD

**Issue by himslm01** [containerd/nerdctl#537] opened 2021-11-18 23:14 UTC
I have a long and complicated build process.

One Dockerfile downloads source code from a lot of repositories to build a single source image.

A second Dockerfile copies the source code and compiles it as an application is built. This second Dockerfile is built multiple times with different build arguments to build for different architectures from the same source - hence the source is downloaded once but the application is built many times.

The second Dockerfile uses the syntax `COPY --from=<image:tag> /source /destination`

for example

```
COPY --from=ffbuild_source:latest ${ffbuild_prefix}/source/osxcross /opt/osxcross
```

This works with `docker` CLI and docker daemon.

This does not work with `nerdctl` and containerd.

I get the error `=> ERROR FROM docker.io/library/ffbuild_source:latest`
followed by `error: failed to solve: failed to load cache key: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed`

I can see the image exists:
```
$ nerdctl image ls|grep ffbuild_source
ffbuild_source      latest    150de05e5fb9    24 hours ago    845.3 MiB
```

This is the full command and error

```nerdctl build \
	--build-arg http_proxy="" \
	--build-arg https_proxy="" \
	--build-arg ffbuild_extra_version="static_osx_x86_64_202111172307" \
	--build-arg AR="/opt/osxcross/target/bin/x86_64-apple-darwin15-ar" \
	--build-arg AS="/opt/osxcross/target/bin/x86_64-apple-darwin15-nasm" \
	--build-arg CC="/opt/osxcross/target/bin/x86_64-apple-darwin15-cc" \
	--build-arg CPP="/opt/osxcross/target/bin/x86_64-apple-darwin15-cc -E" \
	--build-arg CXX="/opt/osxcross/target/bin/x86_64-apple-darwin15-c++" \
	--build-arg DLLTOOL="/opt/osxcross/target/bin/x86_64-apple-darwin15-dlltool" \
	--build-arg LD="/opt/osxcross/target/bin/x86_64-apple-darwin15-ld" \
	--build-arg OBJDUMP="/opt/osxcross/target/bin/x86_64-apple-darwin15-ObjectDump" \
	--build-arg PKG_CONFIG="/opt/osxcross/target/bin/x86_64-apple-darwin15-pkg-config --static" \
	--build-arg RANLIB="/opt/osxcross/target/bin/x86_64-apple-darwin15-ranlib" \
	--build-arg STRIP="/opt/osxcross/target/bin/x86_64-apple-darwin15-strip" \
	--build-arg OSXCROSS_PKG_CONFIG_USE_NATIVE_VARIABLES="1" \
	--build-arg ffbuild_arch="osx_x86_64" \
	--build-arg ffbuild_host="x86_64-apple-darwin15" \
	--build-arg ffbuild_boost="" \
	--build-arg ffbuild_cflags="" \
	--build-arg ffbuild_ldflags="" \
	--build-arg ffbuild_path="/opt/osxcross/target/bin:" \
	--build-arg ffbuild_target_openssl="darwin64-x86_64-cc" \
	--build-arg ffbuild_target_vpx="x86_64-darwin15-gcc" \
	--build-arg ffbuild_cross="x86_64-apple-darwin15-" \
	--build-arg ffbuild_cmake="-DCMAKE_OSX_SYSROOT=/opt/osxcross/target/SDK/MacOSX10.11.sdk -DCMAKE_EXE_LINKER_FLAGS=\"-rpath @executable_path/\"" \
	--build-arg ffbuild_cmake_toolchain="SET(CMAKE_SYSTEM_NAME Darwin)\\nSET(CMAKE_C_COMPILER \${CC})\\nSET(CMAKE_AR_COMPILER \${AR})\\nSET(CMAKE_CXX_COMPILER \${CXX})\\nSET(CMAKE_LINKER \${LD})\\nSET(CMAKE_RC_COMPILER \${WINDRES})\\nSET(CMAKE_ASM_YASM_COMPILER \${AS})\\nSET(CMAKE_FIND_ROOT_PATH \${ffbuild_prefix})\\nSET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)\\nSET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)\\nSET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)\\n" \
	-t ffbuild_osx_x86_64_static_libs:latest \
	src/build/libs
[+] Building 2.6s (8/70)                                                                                                                                                                            
 => [internal] load build definition from Dockerfile                                                                                                                                           0.0s
 => => transferring dockerfile: 21.01kB                                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                                              0.0s
 => => transferring context: 2B                                                                                                                                                                0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                                                                                                1.8s
 => CACHED [stage-0  1/64] FROM docker.io/library/ubuntu:20.04@sha256:626ffe58f6e7566e00254b638eb7e0f3b11d4da9675088f4781a50ae288f3322                                                         0.0s
 => => resolve docker.io/library/ubuntu:20.04@sha256:626ffe58f6e7566e00254b638eb7e0f3b11d4da9675088f4781a50ae288f3322                                                                          0.0s
 => ERROR FROM docker.io/library/ffbuild_source:latest                                                                                                                                         0.6s
 => => resolve docker.io/library/ffbuild_source:latest                                                                                                                                         0.6s
 => CANCELED FROM docker.io/library/ffbuild_download:latest                                                                                                                                    0.6s
 => => resolve docker.io/library/ffbuild_download:latest                                                                                                                                       0.6s
 => CANCELED FROM docker.io/library/ffbuild_patch:latest                                                                                                                                       0.6s
 => => resolve docker.io/library/ffbuild_patch:latest                                                                                                                                          0.6s
 => CANCELED [stage-0  2/64] RUN apt-get update  && DEBIAN_FRONTEND=noninteractive apt-get -y install         build-essential         gcc-multilib     g++-multilib     binutils-multiarch     0.6s
------                                                                                                                                                                                              
 > FROM docker.io/library/ffbuild_source:latest:
------
Dockerfile:131
--------------------
 129 |         OSXCROSS_SDK_VERSION="${ffbuild_macosx_development_target_ver}" \
 130 |         MACOSX_DEPLOYMENT_TARGET="${ffbuild_macosx_development_target_ver}"
 131 | >>> COPY --from=ffbuild_source:latest ${ffbuild_prefix}/source/osxcross /opt/osxcross
 132 |     COPY --from=ffbuild_download:latest ${ffbuild_prefix}/downloads/MacOSX10.11.sdk.tar.xz /opt/osxcross/tarballs/
 133 |     RUN if ( test "osx_x86_64" = "${ffbuild_arch}" ) ; then \
--------------------
error: failed to solve: failed to load cache key: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
FATA[0002] unrecognized image format```

One caveat - I'm running the build in a Lima VM executed by RancherDesktop - I don't know whether that makes any difference.

**Comment by AkihiroSuda** [comment] 2021-11-19 03:35
Duplicate of https://github.com/containerd/nerdctl/issues/434

Hard to implement this🥲. Help wanted.

**Closed by AkihiroSuda** 2021-11-19 03:35 UTC
