### ISSUE TITLE
nerdctl does not create directory when mounting a not existing directory from host

### ISSUE THREAD

**Issue by a14stoner** [containerd/nerdctl#899] opened 2022-03-14 11:46 UTC
When i try to make this command:
`sudo nerdctl run -d --name test -h test -v /u02/TEST_DIRECTORY:/TEST_DIRECTORY image_name:1.12`

and this directory does not exist the following error occurs: 
```
FATA[0000] failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/u02/TEST_DIRECTORY" to rootfs at "/TEST_DIRECTORY": stat /u02/TEST_DIRECTORY: no such file or directory: unknown
```
It would be cool if nerdctl creates a not existing directory just as docker does. 

Nerdctl version: 

```
sudo nerdctl --version

nerdctl version 0.17.1
```

OS Version: 

```
cat /etc/os-release

NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.4 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.4:GA"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.4"
```

**Comment by AkihiroSuda** [comment] 2022-03-14 13:15
Seems a duplicate of https://github.com/containerd/nerdctl/issues/472

**Closed by AkihiroSuda** 2022-03-14 13:15 UTC
