### ISSUE TITLE
nerctl commit  image couldn‘t  push

### ISSUE THREAD

**Issue by xjdtd** [containerd/nerdctl#3248] opened 2024-07-25 01:19 UTC
### Description

[root@node02 ~]# nerdctl -n k8s.io ps |grep  gitlab-runner
926a762b2a98    registry.xjd.com:5443/cicd/gitlab-runner:v17.2.0                                    "/usr/bin/dumb-init …"     12 hours ago    Up                 k8s://cicd/gitlab-runner-78cbbdc498-8s77r/gitlab-runner
ead863474fe8    registry.aliyuncs.com/google_containers/pause:3.9                                   "/pause"                   12 hours ago    Up                 k8s://cicd/gitlab-runner-78cbbdc498-8s77r

[root@node02 ~]# nerdctl -n k8s.io commit 926a762b2a98 registry.xjd.com:5443/cicd/gitlab-runner:v17.2.1
WARN[0000] Image lacks label "nerdctl/platform", assuming the platform to be "linux/amd64" 
sha256:8f0608ae860357cbb3efec565072070f2b9fc44c674c418ba9a04df57f8bd341

[root@node02 ~]# nerdctl -n k8s.io push registry.xjd.com:5443/cicd/gitlab-runner:v17.2.1
FATA[0000] failed to create a tmp single-platform image "registry.xjd.com:5443/cicd/gitlab-runner:v17.2.1-tmp-reduced-platform": content digest sha256:560c024910bebac6b404791af28ebd48a8289303b8377d17b67ffdfe52754f2a: not found 
[root@node02 ~]# 

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

commit image could push

### What version of nerdctl are you using?

[root@node02 ~]# nerdctl --version
nerdctl version 1.7.6

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by apostasie** [comment] 2024-07-25 22:50
@xjdtd 

I do not have access to your private repo and image.

I can confirm that the following is working:
```
nerdctl pull bitnami/gitlab-runner:latest
nerdctl run -d --name gr bitnami/gitlab-runner:latest
nerdctl commit 297e187df139 apostasie/test
nerdctl push apostasie/test
```

Can you provide a reproducible case for your problem?

(* `WARN[0000] Image lacks label "nerdctl/platform", assuming the platform to be "linux/amd64"` is certainly giving a pointer to whats going on, but information on how your produced that / built the image would help a lot)

**Comment by memeda3n** [comment] 2024-07-26 10:00
I meet the same  problem too.
I commit a k8s pod with nerdctl, but , I can not push it to Harbor。

**Comment by apostasie** [comment] 2024-07-26 15:29
@memeda3n can you provide steps to reproduce?

**Comment by apostasie** [comment] 2024-07-30 07:21
@AkihiroSuda probably a duplicate of #827

**Closed** 2024-07-30 07:43 UTC
Labels: duplicate

**Comment by memeda3n** [comment] 2024-07-31 10:19
@apostasie
I can't try it because our service can only run within the internal network.

Here are the details:
In our Kubernetes cluster, I want to commit a running pod to create an image. 
nerdctl version is 1.7.6
containerd version is 1.6.24

Here are the steps I'm following:
![nerdctl](https://github.com/user-attachments/assets/e3a3ba57-643b-4771-9afb-799c9332ee8f)

when I save the image as tar.gz ,also case the same issue.
