### ISSUE TITLE
[main regression] `nerdctl network rm` fails with `no running task found`

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#1582] opened 2022-12-01 13:05 UTC
```console
$ nerdctl network create foo
2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae

$ nerdctl network rm foo
FATA[0000] no running task found: task 0ceb5ec84e8c8ab55a75eaa4d93482359142417bed2dee1b740137c7affbb6d9 not found: not found 
```

Regression in 150547f18d6485f76dad21db142cb911042dda7a
- https://github.com/containerd/nerdctl/pull/1569

Blocker for releasing v1.1

**Comment by fahedouch** [comment] 2022-12-01 14:49
Closed by #1584

**Closed by fahedouch** 2022-12-01 14:49 UTC
Labels: bug, priority/high

**Comment by fahedouch** [comment] 2022-12-02 16:27
@djdongjin  how do you reproduce this error on local ?

**Comment by djdongjin** [comment] 2022-12-02 16:34
Same as in #1593 which changes .Run() to .AssertOK() then run integration test. In my local there are 2 failures (in PR description), in the PR CI there is only one failure.

**Comment by djdongjin** [comment] 2022-12-02 16:38
Maybe because it’s flaky or the use of .Run() is expected? Could you please take a look at the draft PR and see if these changes to AssertOK() make sense (if so, there is a corresponding failure in the ci link above)

thanks!

**Comment by fahedouch** [comment] 2022-12-03 22:53
@djdongjin this should be fixed by https://github.com/containerd/nerdctl/pull/1599, PTAL!
