### ISSUE TITLE
[Windows] Networking doesn't work

### ISSUE THREAD

**Issue by lippertmarkus** [containerd/nerdctl#559] opened 2021-11-23 17:06 UTC
When using `nerdctl run` to start a Windows container, networking doesn't work as there is no ethernet adapter attached:

```powershell
.\nerdctl.exe pull mcr.microsoft.com/windows/nanoserver:1809
.\nerdctl.exe run --rm mcr.microsoft.com/windows/nanoserver:1809 cmd /c ipconfig

# Windows IP Configuration
```

Same behaviour like with `ctr`:
```powershell
./ctr.exe i pull mcr.microsoft.com/windows/nanoserver:1809
./ctr.exe run -rm  mcr.microsoft.com/windows/nanoserver:1809 test cmd /c ipconfig

# Windows IP Configuration
```

With `crictl` it works however:
```powershell
.\crictl.exe pull mcr.microsoft.com/windows/nanoserver:1809
$POD_ID=(./crictl runp .\pod.json)
$CONTAINER_ID=(./crictl create $POD_ID .\container.json .\pod.json)
./crictl start $CONTAINER_ID
.\crictl.exe exec $CONTAINER_ID cmd /c ipconfig

# Windows IP Configuration
#
# Ethernet adapter vEthernet (3cceb90e9342cc0a23db648c9c4da002a329d285ba3733e8feb666a374e9f842_nat):
#
#   Connection-specific DNS Suffix  . : 
#   Link-local IPv6 Address . . . . . : fe80::1d7f:3f4c:efb5:457b%15
#   IPv4 Address. . . . . . . . . . . : 172.30.197.170
#   Subnet Mask . . . . . . . . . . . : 255.255.240.0
#   Default Gateway . . . . . . . . . : 172.30.192.1
```

with `pod.json`:
```json
{
  "metadata": {
    "name": "mycont-sandbox",
    "namespace": "default",
    "attempt": 1,
    "uid": "hdishd83djaidwnduwk28basb"
  },
  "log_directory": "/tmp",
  "linux": {
  }
}
```

and `container.json`:
```json
{
  "metadata": {
      "name": "mycont"
  },
  "image":{
      "image": "mcr.microsoft.com/windows/nanoserver:1809"
  },
  "command": [
      "cmd",
      "/c",
      "ping -t 127.0.0.1"
  ],
  "log_path":"mycont.0.log",
  "linux": {
  }
}
```

Without having any knowledge about the internals, I would assume it's because `crictl` uses a pod sandbox where networking is set up for and `ctr`/`nerdctl` doesn't?

cc @jsturtevant

**Comment by jsturtevant** [comment] 2021-11-30 16:36
Looks like CTR has a flag for CNI that needs to be enabled: 

- https://github.com/containerd/containerd/blob/af1a0908d06b4f7db4a11bfc67ecc2f34baeb04b/cmd/ctr/commands/run/run.go#L210-L214 
- https://github.com/containerd/containerd/blob/af1a0908d06b4f7db4a11bfc67ecc2f34baeb04b/cmd/ctr/commands/run/run.go#L137

Could you try that and see if CTR is working with that flag?


For nerdctl, it look like the network is set up via a OCI hook.  Something doesn't seem to be hooked up correctly for Windows.  The hook is here:

https://github.com/containerd/nerdctl/blob/fae1696fba90fb3b1d2bb9098ea102b6ca1e4859/cmd/nerdctl/internal.go#L24-L34

and 

Here is where the network created with that hook:

https://github.com/containerd/nerdctl/blob/288848d0b93bb05648b8c961568f0c04902205e2/pkg/ocihook/ocihook.go#L175

**Comment by jsturtevant** [comment] 2021-11-30 16:37
I will see if I can get this wired up properly.

**Comment by lippertmarkus** [comment] 2021-12-01 08:37
The flag is only available on Linux:
https://github.com/containerd/containerd/blob/af1a0908d06b4f7db4a11bfc67ecc2f34baeb04b/cmd/ctr/commands/run/run_unix.go#L82-L85

but not on Windows:
https://github.com/containerd/containerd/blob/af1a0908d06b4f7db4a11bfc67ecc2f34baeb04b/cmd/ctr/commands/run/run_windows.go#L33

**Comment by lippertmarkus** [comment] 2021-12-01 09:46
I tried adding the `cni` flag to the `platformRunFlags` for Windows as well to try it out. It seems that it tries to do the right thing but fails in the end:
```
PS C:\Program Files\containerd> .\myctr.exe run --rm --cni mcr.microsoft.com/windows/nanoserver:1809 test7 cmd /c ipconfig
ctr: plugin type="nat" name="nat" failed (add): netplugin failed: "{\"level\":\"debug\",\"msg\":\"[cni-net] Plugin wcn-net version .\",\"time\":\"2021-12-01T09:45:51Z\"}\n{\"level\":\"debug\",\"msg\":\"[net] Ne
twork interface: {Index:4 MTU:1500 Name:Ethernet HardwareAddr:00:15:5d:de:e3:37 Flags:up|broadcast|multicast} with IP addresses: [fe80::7521:b0fb:3b27:e219/64 10.1.0.149/8]\",\"time\":\"2021-12-01T09:45:51Z\"}\
n{\"level\":\"debug\",\"msg\":\"[net] Network interface: {Index:1 MTU:-1 Name:Loopback Pseudo-Interface 1 HardwareAddr: Flags:up|loopback|multicast} with IP addresses: [::1/128 127.0.0.1/8]\",\"time\":\"2021-12
-01T09:45:51Z\"}\n{\"level\":\"debug\",\"msg\":\"[net] Network interface: {Index:12 MTU:1500 Name:vEthernet (nat) HardwareAddr:00:15:5d:6e:5a:c1 Flags:up|broadcast|multicast} with IP addresses: [fe80::4d9f:83a4
:1a73:30c0/64 172.27.16.1/20]\",\"time\":\"2021-12-01T09:45:51Z\"}\n{\"level\":\"debug\",\"msg\":\"[cni-net] Plugin started.\",\"time\":\"2021-12-01T09:45:51Z\"}\n{\"level\":\"debug\",\"msg\":\"[cni-net] Proces
sing ADD command with args {ContainerID:default-test7 Netns:/proc/2604/ns/net IfName:eth0 Args: Path:/opt/cni/bin}.\",\"time\":\"2021-12-01T09:45:51Z\"}\n{\"level\":\"debug\",\"msg\":\"[cni-net] Read network co
nfiguration \\u0026{CniVersion:0.2.0 Name:nat Type:nat Ipam:{Type: Environment: AddrSpace: Subnet:172.27.16.0/20 Address: QueryInterval: Routes:[{Dst:{IP:\\u003cnil\\u003e Mask:\\u003cnil\\u003e} GW:\\u003cnil\
\u003e}]} DNS:{Nameservers:[] Domain: Search:[] Options:[]} OptionalFlags:{LocalRoutePortMapping:false AllowAclPortMapping:false} RuntimeConfig:{PortMappings:[] DNS:{Servers:[] Searches:[] Options:[]}} Addition
alArgs:[]}.\",\"time\":\"2021-12-01T09:45:51Z\"}\n{\"level\":\"debug\",\"msg\":\"Parsing port mappings from []\",\"time\":\"2021-12-01T09:45:51Z\"}\n{\"level\":\"debug\",\"msg\":\"[cni-net] Found network 7d46e0
f9-b777-42bc-9c62-5486ab3c0c44 with subnet [{{172.27.16.0 fffff000} 172.27.16.1 []}].\",\"time\":\"2021-12-01T09:45:51Z\"}\n{\"level\":\"debug\",\"msg\":\"[cni-net] Creating a new Endpoint\",\"time\":\"2021-12-
01T09:45:51Z\"}\n{\"level\":\"debug\",\"msg\":\"hcn::HostComputeEndpoint::Create id=\",\"time\":\"2021-12-01T09:45:51Z\"}\n{\"level\":\"debug\",\"msg\":\"hcn::HostComputeEndpoint::Create JSON: {\\\"Name\\\":\\\
"default-test7_nat\\\",\\\"HostComputeNetwork\\\":\\\"7d46e0f9-b777-42bc-9c62-5486ab3c0c44\\\",\\\"IpConfigurations\\\":[{}],\\\"Dns\\\":{},\\\"Routes\\\":[{\\\"NextHop\\\":\\\"172.27.16.1\\\",\\\"DestinationPr
efix\\\":\\\"0.0.0.0/0\\\"}],\\\"SchemaVersion\\\":{\\\"Major\\\":2,\\\"Minor\\\":0}}\",\"time\":\"2021-12-01T09:45:51Z\"}\n{\"level\":\"debug\",\"msg\":\"hcn::HostComputeEndpoint::AddNamespaceEndpoint id=f2960
3ad-4ae0-49a8-8491-c9b23853fa9a\",\"time\":\"2021-12-01T09:45:51Z\"}\n{\"level\":\"debug\",\"msg\":\"hcn::HostComputeNamespace::ModifyNamespaceSettings id=/proc/2604/ns/net\",\"time\":\"2021-12-01T09:45:51Z\"}\
npanic: invalid GUID length: 17\n\ngoroutine 1 [running]:\ngithub.com/Microsoft/windows-container-networking/vendor/github.com/Microsoft/hcsshim/internal/guid.FromString(0xc0000a1660, 0x11, 0x0, 0x0)\n\t/home/n
agiesek/repo/gopath/src/github.com/Microsoft/windows-container-networking/vendor/github.com/Microsoft/hcsshim/internal/guid/guid.go:32 +0x297\ngithub.com/Microsoft/windows-container-networking/vendor/github.com
/Microsoft/hcsshim/hcn.modifyNamespace(0xc0000a1660, 0x11, 0xc00009ed20, 0x70, 0xc00009ed20, 0x70, 0x0)\n\t/home/nagiesek/repo/gopath/src/github.com/Microsoft/windows-container-networking/vendor/github.com/Micr
osoft/hcsshim/hcn/hcnnamespace.go:168 +0x54\ngithub.com/Microsoft/windows-container-networking/vendor/github.com/Microsoft/hcsshim/hcn.ModifyNamespaceSettings(0xc0000a1660, 0x11, 0xc000032840, 0x35, 0x40)\n\t/h
ome/nagiesek/repo/gopath/src/github.com/Microsoft/windows-container-networking/vendor/github.com/Microsoft/hcsshim/hcn/hcnnamespace.go:383 +0x137\ngithub.com/Microsoft/windows-container-networking/vendor/github
.com/Microsoft/hcsshim/hcn.AddNamespaceEndpoint(0xc0000a1660, 0x11, 0xc0000a3590, 0x24, 0xc00007c000, 0x30)\n\t/home/nagiesek/repo/gopath/src/github.com/Microsoft/windows-container-networking/vendor/github.com/
Microsoft/hcsshim/hcn/hcnnamespace.go:405 +0x1f9\ngithub.com/Microsoft/windows-container-networking/network.(*networkManager).CreateEndpoint(0xc00007a060, 0xc0000a3410, 0x24, 0xc0000d2000, 0xc0000a1660, 0x11, 0
x0, 0x0, 0x0)\n\t/home/nagiesek/repo/gopath/src/github.com/Microsoft/windows-container-networking/network/manager.go:131 +0x23b\ngithub.com/Microsoft/windows-container-networking/common/core.(*netPlugin).Add(0x
c000004680, 0xc00007e310, 0x0, 0x0)\n\t/home/nagiesek/repo/gopath/src/github.com/Microsoft/windows-container-networking/common/core/network.go:172 +0x83c\ngithub.com/Microsoft/windows-container-networking/vendo
r/github.com/containernetworking/cni/pkg/skel.(*dispatcher).checkVersionAndCall(0xc000063e98, 0xc00007e310, 0x5cc600, 0xc00007a690, 0xc000063e80, 0x0, 0x28)\n\t/home/nagiesek/repo/gopath/src/github.com/Microsof
t/windows-container-networking/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:185 +0x260\ngithub.com/Microsoft/windows-container-networking/vendor/github.com/containernetworking/cni/pkg/skel.(*dispa
tcher).pluginMain(0xc000063e98, 0xc000063e80, 0x0, 0xc000063e68, 0x5cc600, 0xc00007a690, 0x59d28d, 0x11, 0x53df1a)\n\t/home/nagiesek/repo/gopath/src/github.com/Microsoft/windows-container-networking/vendor/gith
ub.com/containernetworking/cni/pkg/skel/skel.go:221 +0x550\ngithub.com/Microsoft/windows-container-networking/vendor/github.com/containernetworking/cni/pkg/skel.PluginMainWithError(...)\n\t/home/nagiesek/repo/g
opath/src/github.com/Microsoft/windows-container-networking/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:286\ngithub.com/Microsoft/windows-container-networking/cni.(*Plugin).Execute(0xc000006038,
0x5cc580, 0xc000004680, 0x0, 0xc000006030)\n\t/home/nagiesek/repo/gopath/src/github.com/Microsoft/windows-container-networking/cni/plugin.go:49 +0x225\ngithub.com/Microsoft/windows-container-networking/common/c
ore.Core()\n\t/home/nagiesek/repo/gopath/src/github.com/Microsoft/windows-container-networking/common/core/core.go:47 +0x29c\nmain.main()\n\t/home/nagiesek/repo/gopath/src/github.com/Microsoft/windows-container
-networking/plugins/nat/nat_windows.go:16 +0x27\n"
```

**Comment by jsturtevant** [comment] 2021-12-01 16:30
thanks for trying it out and logging the issue on containerd 💯 

For nerdctl implementation, it looks like the current use of OCI hooks will not work as they are POSIX only: https://github.com/opencontainers/runtime-spec/blob/v1.0.2/config.md#posix-platform-hooks.  A quick look through the hcshim code showed they seem to be implemented for LCOW.

I am guessing we will need to create the network during the run flow (similar to cri flow works) and then pass that information to the OCI spec as defined here: https://github.com/opencontainers/runtime-spec/blob/v1.0.2/config-windows.md#network 

@AkihiroSuda do you have any input before I take  look at implementing this?

**Comment by AkihiroSuda** [comment] 2021-12-01 16:31
Why can't Windows support OCI hooks?

**Comment by AkihiroSuda** [comment] 2021-12-01 16:33
> I am guessing we will need to create the network during the run flow (similar to cri flow works) and then pass that information to the OCI spec as defined here:

Does this work with the restart manager (--restart=always)?
On Linux it doesn't work, so it's implemented in the hooks.

**Comment by jsturtevant** [comment] 2021-12-01 16:46
I am not sure why it doesn't have support. Just inferring from the OCI docs and hcsshim code.  spoke briefly with @dcantah and it sounds like it should be technically possible but would need implementation.  

> Does this work with the restart manager (--restart=always)?
> On Linux it doesn't work, so it's implemented in the hooks.

I will have to experiment to figure this out.

**Comment by lippertmarkus** [comment] 2021-12-19 15:21
Thanks to @kevpar I made networking work via `ctr:`:
```
./ctr.exe run --cni -rm -t mcr.microsoft.com/windows/nanoserver:1809 test cmd /c ipconfig

Windows IP Configuration

Ethernet adapter vEthernet (default-test_nat):

  Connection-specific DNS Suffix  . :
  Link-local IPv6 Address . . . . . : fe80::a527:27d2:6f6a:6d53%23
  IPv4 Address. . . . . . . . . . . : 172.27.19.133
  Subnet Mask . . . . . . . . . . . : 255.255.240.0
  Default Gateway . . . . . . . . . : 172.27.16.1
```

Maybe that implementation in https://github.com/containerd/containerd/pull/6304 helps you for nerdctl

**Comment by jsturtevant** [comment] 2022-01-05 16:29
> Maybe that implementation in [containerd/containerd#6304](https://github.com/containerd/containerd/pull/6304) helps you for nerdctl

That is one way to do it but would be different form the Linux implementation here. I also think it might have issues as pointed out above with the flag `--restart=always`.

I've looked into the OCI hooks and there doesn't seem to be any reason it can't be supported in hcsshim it just hasn't been implemented for Windows.  I plan to get a prototype of that working to gauge effort and feasibility and will update here.

**Comment by kkbruce** [comment] 2022-07-15 07:46
In the beginning, I installed it through [install-containerd-runtime.ps1](https://github.com/microsoft/Windows-Containers/blob/Main/helpful_tools/Install-ContainerdRuntime/install-containerd-runtime.ps1), because the specified SYMLINKD  [directory](https://github.com/microsoft/windows-container-networking/issues/70#issuecomment-1185231433) was missing, so the `--cni` of `ctr` could not be used.

After solving the problems of `ctr` and `--cni`, I then tested `nerdctl` and found that there are similar problems. Provide my environment settings, and whether it can provide a useful solution.

---

if run `nerdctl network ls`, command auto-generate  `nerdctl-nat.conflist` file and see two `nat` network: 

```
PS C:\> nerdctl network ls
NETWORK ID    NAME    FILE
              nat     C:\Program Files\containerd\cni\conf\0-containerd-nat.conf
0             nat     C:\Program Files\containerd\cni\conf\nerdctl-nat.conflist
              host
              none
```

nerdctl-nat.conflist content:

```
{
  "cniVersion": "1.0.0",
  "name": "nat",
  "nerdctlID": 0,
  "nerdctlLabels": {},
  "plugins": [
    {
      "type": "nat",
      "master": "Ethernet",
      "ipam": {
        "routes": [
          {
            "gateway": "10.4.0.1"
          }
        ],
        "subnet": "10.4.0.0/24",
        "type": ""
      }
    }
  ]
}
```

```
PS C:\> nerdctl -v
nerdctl version 0.21.0
```

```
PS C:\> nerdctl info
Client:
 Namespace:     default
 Debug Mode:    false

Server:
 Server Version: v1.6.6
 Storage Driver: windows
 Logging Driver: json-file
 Cgroup Driver:
 Cgroup Version:
 Plugins:
  Log: fluentd journald json-file
  Storage: windows-lcow windows
 Security Options:
 Kernel Version:
 Operating System:
 OSType: windows
 Architecture:
 CPUs: 0
 Total Memory: 0B
 Name: labtestcontaine
 ID: 2755fc58-0723-4ec1-91b9-c652d11765de
 ```

Running with `--net nat`: 

```
PS C:\> nerdctl run --rm --net nat mcr.microsoft.com/windows/nanoserver:ltsc2022 ipconfig

Windows IP Configuration
```

The run result of `ctr` with `--cni`:

```
PS C:\> ctr run --cni --rm mcr.microsoft.com/windows/nanoserver:ltsc2022 test ipconfig

Windows IP Configuration

Ethernet adapter vEthernet (default-test_nat):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::fdd7:f487:e1fc:be8f%17
   IPv4 Address. . . . . . . . . . . : 172.20.86.86
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . : 172.20.80.1
```

**Comment by lippertmarkus** [comment] 2022-07-15 08:14
@kkbruce Networking support for Windows is not implemented yet in nerdctl. Currently networking only works with crictl and ctr.

**Comment by kkbruce** [comment] 2022-07-15 08:59
@lippertmarkus Thanks for your info. Let's take a look at crictl first, and we can only look forward to its implementation.

**Comment by leandroscardua** [comment] 2023-02-03 11:53
He There,

Thank you for the hard work on nerdctl :D
Secondly, Do we have any update on it? to support network on windows container?

**Comment by jsturtevant** [comment] 2023-02-06 18:55
looks like it is in progress with #1953

**Comment by leandroscardua** [comment] 2023-02-07 11:22
Thank for the update @jsturtevant

**Comment by jsturtevant** [comment] 2023-03-22 17:08
It should, though note it only works with NAT networks right now.

**Comment by leandroscardua** [comment] 2023-03-22 17:12
It will be an amazing start :D

**Comment by alkreddy** [comment] 2023-07-19 00:44
I can confirm that version 1.4.0 of nerdctl release does not exhibit this issue. The solution may have been released in an earlier version but I verified it with the latest at the time of this post

**Closed** 2023-07-19 01:30 UTC
Labels: platform/Windows/Non-WSL2
