### ISSUE TITLE
Cannot read mounted volumes as any user other than root

### ISSUE THREAD

**Issue by hoffmanr-cshs** [containerd/nerdctl#362] opened 2021-09-15 15:33 UTC
I am creating and running an image with `nerdctl compose`, using a simple "volumes" line in the compose file. I am running nerdctl inside lima-vm on MacOS using default configuration.

```
# excerpt from sample compose.yaml
services:
  my_container:
    build: .
    volumes:
      - ./files:/files
```

When I get into the container's shell, I can see the mounted volume as expected:

```
> lima nerdctl compose up -d
> lima nerdctl exec -it my_app_my_container_1 bash
>> ls -la /
...
drwxr-xr-x   2 root   root    4096 Sep  2 00:00 lib64
drwxr-xr-x   1 nobody nogroup  256 Sep 15 13:29 files   # <--- my shared volume
drwxr-xr-x   2 root   root    4096 Sep  2 00:00 media
...
```

In my case, I'm running into the issue trying to run apache in a container. However, no user other than root seems to be able to "see" that volume.

```
>> su -s /bin/bash www-data
>>> ls -la /
...
drwxr-xr-x   2 root   root    4096 Sep  2 00:00 lib64
d?????????   ? ?      ?          ?            ? files   # <--- what does this mean?
drwxr-xr-x   2 root   root    4096 Sep  2 00:00 media
...
```

Is this just something I've fouled up in my own configuration? Or is there some other way volumes should be defined when using `nerdctl compose`?

**Comment by AkihiroSuda** [comment] 2021-09-16 04:38
Duplicate of https://github.com/lima-vm/lima/issues/232
Being fixed in https://github.com/lima-vm/lima/pull/247

**Closed by AkihiroSuda** 2021-09-16 04:38 UTC
Labels: duplicate, platform/macOS
