### ISSUE TITLE
[Compose] support for running with container's network namespace 

### ISSUE THREAD

**Issue by sureshg** [containerd/nerdctl#549] opened 2021-11-21 20:29 UTC
```
  app:
     ....
  tcpdump:
    image: nicolaka/netshoot:latest
    restart: always
    network_mode: "container:app"
    command: [ "tcpdump" ]
```
Running the above compose app throws the following error
`FATA[0000] unsupported network_mode: "container:app" ` 

Container networking is very useful for running debugging sidecars (eg: `tcpdump` or other networking tools)

**Comment by AkihiroSuda** [comment] 2021-11-22 17:17
Duplicate of https://github.com/containerd/nerdctl/issues/421 (Pull requests are welcome)

**Closed by AkihiroSuda** 2021-11-22 17:17 UTC
Labels: enhancement, area/compose
