### ISSUE TITLE
Cannot start previously stopped containers (`plugin type=\"bridge\" failed (add): failed to allocate for range 0: 10.4.0.4 has been allocated to default-XXXX, duplicate allocation is not allowed"`)

### ISSUE THREAD

**Issue by max-wittig** [containerd/nerdctl#665] opened 2022-01-04 15:12 UTC
Similar to https://github.com/containerd/nerdctl/issues/492

## System

macOS 12.1

```sh
nerdctl version                                                                                                                             
Client:
 Version:       v0.15.0
 Git commit:    b72b5ca14550b2e23a42787664b6182524c5053f

Server:
 containerd:
  Version:      v1.5.8-k3s1
  GitCommit:
```

## How to reproduce

1. Start container: e.g.: `nerdctl run -d -e POSTGRES_PASSWORD=postgres -p 5432:5432 postgres:latest`
2. Stop your container runtime (e.g. Rancher Desktop)
3. Start your container runtime
4. Show existing containers `nerdctl ps --all`
5. Try to start the existing container

```sh
nerdctl start dff170a6c9b1
FATA[0000] failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: time="2022-01-04T15:11:37Z" level=fatal msg="failed to call cni.Setup: plugin type=\"bridge\" failed (add): failed to allocate for range 0: 10.4.0.4 has been allocated to default-dff170a6c9b146701bba04d19ecfc27ae5a26374aeccc87be2f6b1a7993e537a, duplicate allocation is not allowed"
Failed to write to log, write /var/lib/nerdctl/dbb19c5e/containers/default/dff170a6c9b146701bba04d19ecfc27ae5a26374aeccc87be2f6b1a7993e537a/oci-hook.createRuntime.log: file already closed: unknown
```

**Comment by Junnplus** [comment] 2022-01-05 02:22
Duplicate of https://github.com/containerd/nerdctl/issues/458

**Comment by max-wittig** [comment] 2022-01-05 08:32
@Junnplus Okay interesting. I didn't see that issue with this context, but it could make sense. Should I close this one then?

**Comment by AkihiroSuda** [comment] 2022-01-05 09:59
#458 is for rootless, but the OP seems rootful, so not a duplicate

**Comment by max-wittig** [comment] 2022-01-11 15:04
Update: It actually works after a few tries, so after 3-4 times `nerdctl start f01efaea7cce`, it works.

**Comment by stanshih0315** [comment] 2022-02-15 10:20
```bash
> nerdctl start devOraDB
FATA[0000] failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: time="2022-02-15T10:02:36Z" level=fatal msg="failed to call cni.Setup: plugin type=\"bridge\" failed (add): failed to allocate for range 0: 10.4.0.3 has been allocated to default-418e62d24bcd44f0be76e13a7c05ded9140c9cf956d068193042c4b9ed5b5108, duplicate allocation is not allowed"
Failed to write to log, write /var/lib/nerdctl/dbb19c5e/containers/default/418e62d24bcd44f0be76e13a7c05ded9140c9cf956d068193042c4b9ed5b5108/oci-hook.createRuntime.log: file already closed: unknown
> nerdctl ps -a
CONTAINER ID    IMAGE                                                  COMMAND                   CREATED              STATUS     PORTS                     NAMES
418e62d24bcd    docker.io/store/oracle/database-enterprise:12.2.0.1    "/bin/sh -c /bin/bas…"    About an hour ago    Created    0.0.0.0:1521->1521/tcp    devOraDB
8cfcd3da9696    docker.io/library/nginx:alpine                         "/docker-entrypoint.…"    8 minutes ago        Up         0.0.0.0:8080->80/tcp      nginx
> nerdctl start 418e62d24bcd
418e62d24bcd
> nerdctl ps
CONTAINER ID    IMAGE                                                  COMMAND                   CREATED              STATUS    PORTS                     NAMES
418e62d24bcd    docker.io/store/oracle/database-enterprise:12.2.0.1    "/bin/sh -c /bin/bas…"    About an hour ago    Up        0.0.0.0:1521->1521/tcp    devOraDB
8cfcd3da9696    docker.io/library/nginx:alpine                         "/docker-entrypoint.…"    9 minutes ago        Up        0.0.0.0:8080->80/tcp      nginx
```

OS: Windows 10 21H1

**Comment by elegorod** [comment] 2022-06-02 13:18
Also have same issue on Windows.

**Comment by Jiahonzheng** [comment] 2022-09-10 14:14
Any updates?😭

**Comment by AkihiroSuda** [comment] 2022-09-10 14:17
> Any updates?😭

Needs a reproducer

**Comment by dg-it** [comment] 2022-11-18 08:28
> Update: It actually works after a few tries, so after 3-4 times `nerdctl start f01efaea7cce`, it works.
Thanks, this worked.

Same issue on Mac M1 Max Ventura + lima  0.13.0 + nerdctl 1.0.0. After gracefully stopping an oracle xe docker container and lima itself, restarting lima and then 'lima nerdctl start <my-oracle-xe-db> gives:

FATA[0002] failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: time="2022-11-18T08:15:47Z" level=fatal msg="failed to call cni.Setup: plugin type=\"bridge\" failed (add): failed to allocate for range 0: 10.4.0.15 has been allocated to default-363e3264c8187fe7c62a3da5599022a4cec63a97c0db08909ac40fca1b6c45b0, duplicate allocation is not allowed"
Failed to write to log, write /home/<ommitted>/.local/share/nerdctl/1935db59/containers/default/363e3264c8187fe7c62a3da5599022a4cec63a97c0db08909ac40fca1b6c45b0/oci-hook.createRuntime.log: file already closed: unknown 

After some retries/wait time, it works.

**Comment by jandubois** [comment] 2023-01-05 22:18
> Needs a reproducer

@AkihiroSuda I can reproduce it consistently on macOS Monterey (Intel) with Lima 0.14.2:

```
$ limactl --version
limactl version 0.14.2

$ limactl start --tty=false
[...]

$ nerdctl.lima --version
nerdctl version 1.1.0

$ nerdctl.lima run -d --name nginx -p 8080:80 nginx
[...]
cae8a90f488edbe1a54cb23d05065873f3d0bc1c55ed21ac162aff6f9971895b

$ curl -s http://localhost:8080 | grep Welcome
<title>Welcome to nginx!</title>
<h1>Welcome to nginx!</h1>

$ limactl stop
[...]

$ limactl start
[...]

$ nerdctl.lima ps -a
CONTAINER ID    IMAGE                             COMMAND                   CREATED               STATUS     PORTS                   NAMES
cae8a90f488e    docker.io/library/nginx:latest    "/docker-entrypoint.…"    About a minute ago    Created    0.0.0.0:8080->80/tcp    nginx

$ nerdctl.lima start nginx
FATA[0000] failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: time="2023-01-05T22:10:10Z" level=fatal msg="failed to call cni.Setup: plugin type=\"bridge\" failed (add): failed to allocate for range 0: 10.4.0.2 has been allocated to default-cae8a90f488edbe1a54cb23d05065873f3d0bc1c55ed21ac162aff6f9971895b, duplicate allocation is not allowed"
Failed to write to log, write /home/jan.linux/.local/share/nerdctl/1935db59/containers/default/cae8a90f488edbe1a54cb23d05065873f3d0bc1c55ed21ac162aff6f9971895b/oci-hook.createRuntime.log: file already closed: unknown
```

Restarting the VM seems to be an essential step; I have not been able to reproduce it by simply stopping the container.

The issue happens with both rootfull and rootless installations of containerd, and can be reproduced on Alpine as well (using Rancher Desktop).

**Comment by jandubois** [comment] 2023-01-05 22:35
Note that the container restarts properly if you deploy it with `--restart=always`:

```console
$ nerdctl.lima run -d --name nginx --restart=always -p 8080:80 nginx
d761b17ffe563acb55fa5c557b5e5c6d572666b350f5e39ce1f0c4c3a77de3c4

$ curl -s http://localhost:8080 | grep Welcome
<title>Welcome to nginx!</title>
<h1>Welcome to nginx!</h1>

$ limactl stop
[...]

$ limactl start
[...]

$ nerdctl.lima ps -a
CONTAINER ID    IMAGE                             COMMAND                   CREATED               STATUS    PORTS                   NAMES
d761b17ffe56    docker.io/library/nginx:latest    "/docker-entrypoint.…"    About a minute ago    Up        0.0.0.0:8080->80/tcp    nginx

$ curl -s http://localhost:8080 | grep Welcome
<title>Welcome to nginx!</title>
<h1>Welcome to nginx!</h1>
```

**Comment by aogg** [comment] 2023-02-07 15:25
agent

**Comment by litcc** [comment] 2023-03-08 01:50
About the problem of restarting the container after stopping, this error has been there for most of the year, I have this problem is in every boot, restarting the corresponding container will report an error, but when you start again can start normally

![image](https://user-images.githubusercontent.com/13202561/223598279-9d024003-3a56-469e-b63c-7115d0724cc0.png)

**Comment by apostasie** [comment] 2024-08-25 18:52
@max-wittig I believe this got fixed with:
https://github.com/containerd/nerdctl/pull/3356/files#diff-e0596cfbff08dfa3c5d049b51af0bf64607ac3fcd0fd48087b17be54c6632ef6

We have a few duplicates for this:
- #2933
- #3355

**Closed** 2024-08-25 23:16 UTC
Labels: bug, help wanted
