### ISSUE TITLE
nerdctl compose up command doesn't work with my docker-compose.yml

### ISSUE THREAD

**Issue by joaopfg** [containerd/nerdctl#1102] opened 2022-06-07 15:32 UTC
### Description

I built my images successfully using `nerdctl compose build` command. However, at the moment of launching the containers using `nerdctl compose up` command, I get an error.

### Steps to reproduce the issue

My `docker-compose.yml` is more complex than the one I put here but in order to reproduce the issue, this one is enough (it doesn't cause any problems when launching with `docker-compose` CLI).

```
version: '3.7'

services:
  db:
    image: postgres:10.19
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    container_name: db

volumes:
  postgres_data:
```

Run:
`sudo nerdctl compose up`

### Describe the results you received and expected

The logs until the death of the container are:
```
INFO[0000] Creating network nerdctl-issue_default       
INFO[0000] Ensuring image postgres:10.19                
INFO[0000] Creating container db                        
INFO[0000] Attaching to logs                            
db |time="2022-06-07T17:29:09+02:00" level=fatal msg="failed to open \"/var/lib/nerdctl/1935db59/containers/default/6776ee1a399202e9008d1e1e2b26a10ba0deb5b02f842318c6af4d480fb11354/6776ee1a399202e9008d1e1e2b26a10ba0deb5b02f842318c6af4d480fb11354-json.log\", container is not created with `nerdctl run -d`?: stat /var/lib/nerdctl/1935db59/containers/default/6776ee1a399202e9008d1e1e2b26a10ba0deb5b02f842318c6af4d480fb11354/6776ee1a399202e9008d1e1e2b26a10ba0deb5b02f842318c6af4d480fb11354-json.log: no such file or directory"
INFO[0000] Container "db" exited                        
INFO[0000] All the containers have exited               
INFO[0000] Stopping containers (forcibly)               
INFO[0000] Stopping container db 
```

### What version of nerdctl are you using?

0.20.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

No

### Host information

```
Client:
 Namespace:	default
 Debug Mode:	false

Server:
 Server Version: v1.6.4
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Log: json-file
  Storage: aufs native overlayfs
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.13.0-44-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.576GiB
 Name: <computer-name>
 ID: db2396ff-441a-4445-8ddd-e70805ba1bf6
```

**Comment by AkihiroSuda** [comment] 2022-06-08 07:49
Duplicate of 
- https://github.com/containerd/nerdctl/issues/1071

Workaround (thanks to @davebarkerxyz): `nerdctl compose up -d; sleep 2; nerdctl compose logs -f`

**Closed by AkihiroSuda** 2022-06-08 07:49 UTC
Labels: kind/unconfirmed-bug-claim

**Comment by nsmosi** [comment] 2023-02-13 05:54
still after almost a year with new version it is not wokring, !!! same issue still persist
