### ISSUE TITLE
nerdctl compose run does not pass args with dash to the command

### ISSUE THREAD

**Issue by dimaulupov** [containerd/nerdctl#1666] opened 2022-12-18 03:15 UTC
### Description

`nerdctl compose run <service> <command> <args>` passes all args without '-' in front of the name to the command.  
But if arg starts with dash it is treated as a `nerdctl` arg instead of passing it to the command.  

### Steps to reproduce the issue

1. Create compose.yaml with this content:
```yaml
version: "3"
services:
  app:
    image: ubuntu
``` 
3. run `nerdctl compose -f ./compose.yml run app ls --all`
4. Error message displayed: `FATA[0000] unknown flag: --all`

(Instead it should list files)

### Describe the results you received and expected

All `[ARGS]` in the `nerdctl compose run [OPTIONS] SERVICE [COMMAND] [ARGS...]` line are expected to be passed to the command. At least this is a `docker compose` behaviour.

### What version of nerdctl are you using?

Client:
 Version:       v1.0.0
 OS/Arch:       linux/amd64
 Git commit:    c00780a1f5b905b09812722459c54936c9e070e6
 buildctl:
  Version:      v0.11.0-rc3
  GitCommit:    4b220de5058abfd01ff619c9d2ff6b09a049bea0

Server:
 containerd:
  Version:      1.5.9-0ubuntu3.1
  GitCommit:
 runc:
  Version:      1.1.0-0ubuntu1.1

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

Client:
 Namespace:     default
 Debug Mode:    false

Server:
 Server Version: 1.5.9-0ubuntu3.1
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Log: fluentd journald json-file syslog
  Storage: native overlayfs
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-56-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.832GiB
 Name: dev
 ID: 82cec64c-f785-4f3b-9269-52421d19eb1c

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by fahedouch** [comment] 2022-12-19 18:27
it's cobra misbehavior. 
A workaround : `nerdctl compose  -f ./examples/compose-wordpress/docker-compose.yaml run wordpress "ls --all"`

**Comment by djdongjin** [comment] 2022-12-21 15:42
#1671 should fix this issue. Both the original command and the workaround @fahedouch gives work on main branch. Closing now, please feel free to reopen if the issue is not fully fixed.

```shell
# original command
$ sudo nerdctl compose run app ls --all
INFO[0000] Creating network 1666_default
INFO[0000] Ensuring image ubuntu
docker.io/library/ubuntu:latest:                                                  resolved       |++++++++++++++++++++++++++++++++++++++|
...
elapsed: 1.8 s                                                                    total:  29.0 M (16.1 MiB/s)
INFO[0001] Creating container 1666_app_run_d475b580387d
.   bin   dev  home  lib32  libx32  mnt  proc  run   srv  tmp  var
..  boot  etc  lib   lib64  media   opt  root  sbin  sys  usr
# workaround
$ sudo nerdctl compose run app -- ls --all
INFO[0000] Ensuring image ubuntu
INFO[0000] Creating container 1666_app_run_9f537d52e814
.   bin   dev  home  lib32  libx32  mnt  proc  run   srv  tmp  var
..  boot  etc  lib   lib64  media   opt  root  sbin  sys  usr
```

**Closed** 2022-12-21 15:42 UTC
Labels: area/cobra
