### ISSUE TITLE
The output of `nerdctl stats` disappears after a few minutes

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#1278] opened 2022-07-30 06:28 UTC
### Description

The output of `nerdctl stats` disappears after a few minutes

### Steps to reproduce the issue

1. `nerdctl run -d alpine sleep infinity`
2. `nerdctl stats`
3. Wait for a few minute

### Describe the results you received and expected

Received:
```
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O   PIDS
ce15db2ec247   alpine-ce15d   --        -- / --             --        --        --          --
```

Expected: some stats

### What version of nerdctl are you using?

v0.22.0-42-g4c37225

### Host information

```
Client:
 Namespace:     default
 Debug Mode:    false

Server:
 Server Version: v1.6.6
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Log: fluentd journald json-file
  Storage: native overlayfs
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-41-generic
 Operating System: Ubuntu 22.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.59GiB
...
```

**Comment by AkihiroSuda** [comment] 2022-07-30 06:29
@fahedouch PTAL

**Comment by fahedouch** [comment] 2022-07-31 10:03
@AkihiroSuda I tested stats for 15 minutes and didn't get this behavior. I got an empty stats only when I killed the container after this 15 minutes of fetching stats 

````
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   99.81%    0B / 0B             0.00%     920B / 962B   0B / 0B     3
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   100.21%   0B / 0B             0.00%     920B / 962B   0B / 0B     3
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   99.40%    0B / 0B             0.00%     920B / 962B   0B / 0B     3
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   100.41%   0B / 0B             0.00%     920B / 962B   0B / 0B     3
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   100.15%   0B / 0B             0.00%     920B / 962B   0B / 0B     3
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   99.85%    0B / 0B             0.00%     920B / 962B   0B / 0B     3
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   98.59%    0B / 0B             0.00%     920B / 962B   0B / 0B     3
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   101.43%   0B / 0B             0.00%     920B / 962B   0B / 0B     3
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   100.11%   0B / 0B             0.00%     920B / 962B   0B / 0B     3
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   99.95%    0B / 0B             0.00%     920B / 962B   0B / 0B     3
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   40.71%    0B / 0B             0.00%     920B / 962B   0B / 0B     2
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     2
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     2
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     2
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     2
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     2
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     2
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     2
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     2
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     2
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     2
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     2
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     2
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     2
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     2
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     2
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     2
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     2
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.09%     0B / 0B             0.00%     920B / 962B   0B / 0B     2
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   1.16%     0B / 0B             0.00%     920B / 962B   0B / 0B     1
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     1
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     1
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     1
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     1
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     1
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     1
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     1
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     1
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     1
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     1
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     1
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     1
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     1
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     1
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     1
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     1
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     1
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   0.00%     0B / 0B             0.00%     920B / 962B   0B / 0B     1
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   --        -- / --             --        --        --          --
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   --        -- / --             --        --        --          --
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   --        -- / --             --        --        --          --
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   --        -- / --             --        --        --          --
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   --        -- / --             --        --        --          --
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O   PIDS
24c458aa71b2   alpine-24c45   --        -- / --             --        --        --          --
````

Please check if you container is still alive

**Comment by junnplus** [comment] 2022-07-31 10:09
I can't also reproduce.

**Comment by AkihiroSuda** [comment] 2022-08-01 04:44
@fahedouch @junnplus 

I still hit this issue.
Could you test it on a cgroup v2 host such as Ubuntu 22.04 ?

**Comment by junnplus** [comment] 2022-08-01 04:53
@AkihiroSuda Yes, I tested on Ubuntu 22.04 LTS, and it can't reproduce.
```sh
$ sudo nerdctl info
Client:
 Namespace:     default
 Debug Mode:    false

Server:
 Server Version: v1.6.4
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Log: fluentd journald json-file
  Storage: native overlayfs stargz
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-41-generic
 Operating System: Ubuntu 22.04 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 7.74GiB
 Name: lima-default
 ID: 2eef127c-1a0f-466b-b5eb-364a761abbdf

$ sudo nerdctl version
Client:
 Version:       v0.22.0-57-ged3913a
 OS/Arch:       linux/arm64
 Git commit:    ed3913aab0f0a86d3ec8e2f1f53325c68a7f6341
 buildctl:
  Version:      v0.10.3
  GitCommit:    c8d25d9a103b70dc300a4fd55e7e576472284e31

Server:
 containerd:
  Version:      v1.6.4
  GitCommit:    212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:      1.1.2
  GitCommit:    v1.1.2-0-ga916309f

```

**Comment by junnplus** [comment] 2022-08-01 05:12
Sorry, I retried a few times to make sure it's reproducible.

```sh
$ sudo nerdctl info
Client:
 Namespace:     default
 Debug Mode:    false

Server:
 Server Version: v1.6.4
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Log: fluentd journald json-file
  Storage: native overlayfs stargz
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-41-generic
 Operating System: Ubuntu 22.04 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 7.74GiB
 Name: lima-default
 ID: 2eef127c-1a0f-466b-b5eb-364a761abbdf
```

**Comment by AkihiroSuda** [comment] 2022-08-01 05:23
Looks like I can hit the issue with cgroup v1 mode too
```
Server:
 Server Version: v1.6.6
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Log: fluentd journald json-file
  Storage: native overlayfs
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.15.0-43-generic
 Operating System: Ubuntu 22.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.59GiB
```

**Comment by liubin** [comment] 2022-08-03 09:08
I got on cgroup v1:

> route ip+net: netlinkrib: too many open files

It's maybe due to the (netns?) FD leak: https://github.com/containerd/nerdctl/blob/4c37225fa31a63e32162f34bdbc26554430e6dc6/cmd/nerdctl/stats.go#L438

And here, when error occurred, should print it to screen?
https://github.com/containerd/nerdctl/blob/4c37225fa31a63e32162f34bdbc26554430e6dc6/cmd/nerdctl/stats.go#L474-L478

**Comment by AkihiroSuda** [comment] 2022-08-04 07:43
Thank you @liubin , would you mind submitting a PR?

**Comment by fahedouch** [comment] 2022-08-04 07:58
@AkihiroSuda  @liubin I am working on PR to fix this

**Comment by liubin** [comment] 2022-08-04 11:44
> Thank you @liubin , would you mind submitting a PR?

Yes, I'd like to create a PR to fix this.

**Comment by liubin** [comment] 2022-08-04 11:52
@fahedouch Please go on with your work. I only did some verify locally.

**Comment by fahedouch** [comment] 2022-08-25 09:17
Closed by https://github.com/containerd/nerdctl/pull/1298

**Closed by fahedouch** 2022-08-25 09:17 UTC
Labels: bug
