### ISSUE TITLE
hostname -i  command  incorrect record.

### ISSUE THREAD

**Issue by zhujintao** [containerd/nerdctl#1674] opened 2022-12-21 10:00 UTC
### Description

run the  same hostname multiple times , `hostname -i`  command  incorrect record.

```
~ # hostname 
etcd-0
~ # hostname -i
10.4.0.58 10.4.0.63 10.4.0.60 10.4.0.62
~ # cat /etc/hosts 
# <nerdctl>
127.0.0.1	localhost localhost.localdomain
::1		localhost localhost.localdomain
10.4.0.35       bc5a36450e2a etcd-bc5a3
10.4.0.24       efb6e9e224ae etcd-efb6e
10.4.0.58       etcd-0 etcd-e6eb8
10.4.0.29       f617a249fdaa etcd-f617a
10.4.0.14       e410e418c34c curvebs-e410e
10.4.0.59       c8f3f27bc2d9 etcd-c8f3f
10.4.0.63       etcd-0 etcd-0b106
10.4.0.31       d64750239b4b etcd-d6475
10.4.0.60       etcd-0 etcd-c2935
10.4.0.18       e1a77d8e862b etcd-e1a77
10.4.0.62       etcd-0 etcd-f04e1
10.4.0.20       f2da02d6c701 etcd-f2da0
10.4.0.16       dd229a07d8e9 ubuntu-dd229
10.4.0.17       f0a9cef1d4dc ubuntu-f0a9c
# </nerdctl>
~ # ping etcd-0
PING etcd-0 (10.4.0.58): 56 data bytes
^C
--- etcd-0 ping statistics ---
4 packets transmitted, 0 packets received, 100% packet loss
~ # ifconfig
eth0      Link encap:Ethernet  HWaddr 7E:6A:A3:BB:54:D8  
          inet addr:10.4.0.63  Bcast:10.4.0.255  Mask:255.255.255.0
          inet6 addr: fe80::7c6a:a3ff:febb:54d8/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:31 errors:0 dropped:0 overruns:0 frame:0
          TX packets:25 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2090 (2.0 KiB)  TX bytes:1466 (1.4 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:12 errors:0 dropped:0 overruns:0 frame:0
          TX packets:12 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1344 (1.3 KiB)  TX bytes:1344 (1.3 KiB)

```

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

run the  same hostname multiple times , `hostname -i`  command  incorrect record.

### What version of nerdctl are you using?

```
bare-metal-srv14:~/build# nerdctl version
Client:
 Version:	1.0.0
 OS/Arch:	linux/amd64
 Git commit:	<unknown>
 buildctl:
  Version:	0.10.6
  GitCommit:	alpine

Server:
 containerd:
  Version:	v1.6.12
  GitCommit:	a05d175400b1145e5e6a735a6710579d181e7fb0
 runc:
  Version:	1.1.4
  GitCommit:	5fd4c4d144137e991c4acebb2146ab1483a97925
```

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

Others

**Comment by zhujintao** [comment] 2022-12-23 03:46
adding a logic can work correctly
```
if meta.ID != u.id {
   continue
}

```
pkg/dnsutil/hostsstore/updater.go
```
// TODO: cut off entries for the containers in other networks
for ip, nwName := range u.nwNameByIPStr {
	meta := u.metaByIPStr[ip]

	if meta.ID != u.id {
		continue
	}

	if line := createLine(nwName, meta, myNetworks); len(line) != 0 {
		serviceHosts[strings.Join(line, " ")] = ip
	}
}

```

**Comment by fahedouch** [comment] 2022-12-23 17:22
I cannot reproduce this. 



> adding a logic can work correctly
> 
> ```
> if meta.ID != u.id {
>    continue
> }
> ```
> 
> pkg/dnsutil/hostsstore/updater.go
> 
> ```
> // TODO: cut off entries for the containers in other networks
> for ip, nwName := range u.nwNameByIPStr {
> 	meta := u.metaByIPStr[ip]
> 
> 	if meta.ID != u.id {
> 		continue
> 	}
> 
> 	if line := createLine(nwName, meta, myNetworks); len(line) != 0 {
> 		serviceHosts[strings.Join(line, " ")] = ip
> 	}
> }
> ```

this logic drop adding hosts of containers in the same network(s)

**Comment by zhujintao** [comment] 2022-12-25 03:40
> I cannot reproduce this.
> 
> > adding a logic can work correctly
> > ```
> > if meta.ID != u.id {
> >    continue
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > pkg/dnsutil/hostsstore/updater.go
> > ```
> > // TODO: cut off entries for the containers in other networks
> > for ip, nwName := range u.nwNameByIPStr {
> > 	meta := u.metaByIPStr[ip]
> > 
> > 	if meta.ID != u.id {
> > 		continue
> > 	}
> > 
> > 	if line := createLine(nwName, meta, myNetworks); len(line) != 0 {
> > 		serviceHosts[strings.Join(line, " ")] = ip
> > 	}
> > }
> > ```
> 
> this logic drop adding hosts of other containers in the same network(s)

add other containers networks can use other parameters --link .

reproduce test , unable to parse host record correctly  hostname etcd-0 :

```
bare-metal-srv14:~# nerdctl ps -a
CONTAINER ID    IMAGE    COMMAND    CREATED    STATUS    PORTS    NAMES
bare-metal-srv14:~# nerdctl   run  --hostname etcd-0 -it alpine cat /etc/hosts 
# <nerdctl>
127.0.0.1	localhost localhost.localdomain
::1		localhost localhost.localdomain
10.4.0.138      etcd-0 alpine-4d8a2
# </nerdctl>
bare-metal-srv14:~# nerdctl   run  --hostname etcd-0 -it alpine cat /etc/hosts 
# <nerdctl>
127.0.0.1	localhost localhost.localdomain
::1		localhost localhost.localdomain
10.4.0.139      etcd-0 alpine-21cc4
10.4.0.138      etcd-0 alpine-4d8a2
# </nerdctl>
bare-metal-srv14:~# nerdctl   run  --hostname etcd-0 -it alpine cat /etc/hosts 
# <nerdctl>
127.0.0.1	localhost localhost.localdomain
::1		localhost localhost.localdomain
10.4.0.139      etcd-0 alpine-21cc4
10.4.0.138      etcd-0 alpine-4d8a2
10.4.0.140      etcd-0 alpine-a1579
# </nerdctl>
bare-metal-srv14:~# nerdctl   run  --hostname etcd-0 -it alpine hostname -i
10.4.0.138 10.4.0.141 10.4.0.140 10.4.0.139
bare-metal-srv14:~# nerdctl_org   run  --hostname etcd-0 -it alpine ping etcd-0
PING etcd-0 (10.4.0.139): 56 data bytes



```

**Comment by fahedouch** [comment] 2022-12-26 11:10
@zhujintao,  agree it seems a hostsstore bug related . I take care of it :)

**Comment by fahedouch** [comment] 2022-12-29 10:54
@zhujintao, I took some time comparing with docker behavior: 
```
bare-metal-srv14:~# nerdctl   run  --hostname etcd-0 -it alpine hostname -i
10.4.0.138 10.4.0.141 10.4.0.140 10.4.0.139
````
the above behaviour is normal, we can have multiple entries with same hostname in `/etc/hosts` like : 
```
/ # cat /etc/hosts
# <nerdctl>
127.0.0.1       localhost localhost.localdomain
::1             localhost localhost.localdomain
10.4.0.138        etcd-0 alpine-ce409
10.4.0.141        etcd-0 alpine-0f8aa
10.4.0.139        etcd-0 alpine-d743e
# </nerdctl>
/ # ping 
```
Why this is normal ? because each container should be able to communicate with its neighbor(other containers) in the same network using the hostname. 
Now if two container  `A` and `B` have the same hostname `test-host`, when you `ping test-host` from container  `A` it will be resolved to container `A` IP (in other words the container `A` will ping itself and not container `B`) and same approach if you`ping test-host` from container  `B`

I will close this issue. let me know if that makes sense.

**Closed by fahedouch** 2022-12-29 10:54 UTC
Labels: question

**Comment by zhujintao** [comment] 2022-12-29 11:15
> @zhujintao, I took some time comparing with docker behavior:
> 
> ```
> bare-metal-srv14:~# nerdctl   run  --hostname etcd-0 -it alpine hostname -i
> 10.4.0.138 10.4.0.141 10.4.0.140 10.4.0.139
> ```
> 
> the above behaviour is normal, we can have multiple entries with same hostname in `/etc/hosts` like :
> 
> ```
> / # cat /etc/hosts
> # <nerdctl>
> 127.0.0.1       localhost localhost.localdomain
> ::1             localhost localhost.localdomain
> 10.4.0.138        etcd-0 alpine-ce409
> 10.4.0.141        etcd-0 alpine-0f8aa
> 10.4.0.139        etcd-0 alpine-d743e
> # </nerdctl>
> / # ping 
> ```
> 
> Why this is normal ? because each container should be able to communicate with its neighbors(other containers) in the same network using the `hostname`. Now if two container `A` and `B` have the same hostname `test-host`, when you `ping test-host` from container `A` it will be resolved to container `B` IP (resolving hostname depends on the order of entries in `/etc/hosts`) and same approach if you `ping test-host` from container `B`
> 
> Coming back to this issue :
> 
> ```
> bare-metal-srv14:~# nerdctl_org   run  --hostname etcd-0 -it alpine ping etcd-0
> PING etcd-0 (10.4.0.139): 56 data bytes
> ```
> 
> is caused by a non-running container (you cannot send `ICMP packet` to non running container)
> 
> I will close this issue. let me know if that makes sense.

 different from docker working method, but the dokcer working method is expected to be consistent

```
root@bare-metal-srv13:~# docker  run  --hostname etcd-0 -it alpine cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.4	etcd-0
root@bare-metal-srv13:~# docker  run  --hostname etcd-0 -it alpine cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.4	etcd-0
root@bare-metal-srv13:~# docker  run  --hostname etcd-0 -it alpine ping etcd-0
PING etcd-0 (172.17.0.4): 56 data bytes
64 bytes from 172.17.0.4: seq=0 ttl=64 time=0.038 ms
64 bytes from 172.17.0.4: seq=1 ttl=64 time=0.042 ms
^C
--- etcd-0 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.038/0.040/0.042 ms
root@bare-metal-srv13:~# 

```
