### ISSUE TITLE
`nerdctl compose <container>` not implemented

### ISSUE THREAD

**Issue by cfstras** [containerd/nerdctl#375] opened 2021-09-21 10:18 UTC
nerdctl compose does not implement starting single containers.
For example, with a dockerfile containing three containers (`postgres`, `chartmuseum`, `nginx`):

- Running this command will only start `postgres`:
  - `docker-compose up postgres`
- Running this command will start `postgres` and `nginx`:
  - `docker-compose up postgres nginx`

However, `nerdctl compose` will ignore the additional arguments, and always start all three containers.

**Comment by AkihiroSuda** [comment] 2021-09-21 10:21
duplicate of https://github.com/containerd/nerdctl/issues/271

PR is welcome

**Closed by AkihiroSuda** 2021-09-21 10:21 UTC
Labels: duplicate
