### ISSUE TITLE
What about nerdctl export

### ISSUE THREAD

**Issue by Pymann** [containerd/nerdctl#2449] opened 2023-08-24 11:23 UTC
### What is the problem you're trying to solve

For example the pantavisor cli can pvr add app <docker-image> but not work with containerd instead it can add filesystems directly from tar-archives.

Means to work with containerd requires an export of images filesystem in tar-format.

### Describe the solution you'd like

nerdctl export analogously to https://docs.docker.com/engine/reference/commandline/export/

### Additional context

https://docs.pantahub.com/pvr/#pvr-app-commands

**Comment by Jip-Hop** [comment] 2023-08-24 12:10
Looks like a duplicate of https://github.com/containerd/nerdctl/issues/1854

**Comment by fahedouch** [comment] 2023-08-24 12:21
Close for duplication

**Closed** 2023-08-24 12:20 UTC
Labels: kind/feature
