### ISSUE TITLE
Import image issue

### ISSUE THREAD

**Issue by zszeron** [containerd/nerdctl#3700] opened 2024-11-28 03:44 UTC
### Description

I transferred the compressed package to another server using `nerdctl save image:latest | gzip > images.tar.gz`. There was a tag issue. What could be the reason?
```shell
[root@master ~]# nerdctl images | grep registry.k8s.io
registry.k8s.io/ingress-nginx/kube-webhook-certgen    v1.4.4                  a9f03b34a3cb    28 seconds ago    linux/amd64    66.59MB    26.15MB
registry.k8s.io/ingress-nginx/controller              v1.12.0-beta.0          9724476b9289    37 seconds ago    linux/amd64    296.2MB    104.6MB
[root@master ~]# crictl images | grep registry.k8s.io
registry.k8s.io/ingress-nginx/controller:v1.12.0-beta.0     <none>                 11b916a025f02       105MB
registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.4.4   <none>                 a62eeff05ba51       26.2MB
```

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

crictl  and nerdctl   agreement

### What version of nerdctl are you using?

nerdctl version 2.0.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by apostasie** [comment] 2024-12-02 07:50
Duplicate of #3701

**Comment by apostasie** [comment] 2024-12-05 06:01
@AkihiroSuda can we close?

**Closed** 2024-12-05 06:44 UTC
Labels: duplicate
