### ISSUE TITLE
nerctl inspect returns invalid json for multiple containers

### ISSUE THREAD

**Issue by flokain** [containerd/nerdctl#3476] opened 2024-10-01 07:36 UTC
### Description

When running nerdctl inspect <container1> <container2>....it returns invalid json in form of [{container1}][{container2}] instead of  [{container1},{container2}]

This causes `colima` to fail with `--mount-inotify --runtime containerd`. see https://github.com/abiosoft/colima/issues/910 (is closed but not fixed)

### Steps to reproduce the issue

1. sudo nerdctl --namespace 'k8s.io' inspect 4722f9cfc4f3 df6e66bf279e

### Describe the results you received and expected

results
```json
[
    {
        "Id": "4722f9cfc4f320678ceec6640765b959bf1dd56735661301ded967649a90bed2",
        "Created": "2024-09-27T09:18:35.426739516Z",
       ....
    }
]
[
    {
        "Id": "df6e66bf279e61f7cb03f34b86cb667c7b60c5f574f0b7cc19e7ef6013c2a4f2",
        "Created": "2024-09-27T09:18:35.425657747Z",
       ....
    }
]
```

expected

```json
[
    {
        "Id": "4722f9cfc4f320678ceec6640765b959bf1dd56735661301ded967649a90bed2",
        "Created": "2024-09-27T09:18:35.426739516Z",
       ....
    },
    {
        "Id": "df6e66bf279e61f7cb03f34b86cb667c7b60c5f574f0b7cc19e7ef6013c2a4f2",
        "Created": "2024-09-27T09:18:35.425657747Z",
       ....
    }
]
```

### What version of nerdctl are you using?

```
Client:
 Version:       v2.0.0-rc.2
 OS/Arch:       linux/arm64
 Git commit:    cfa7e5388f0d8fb4fe982a47c86e8f141c952d72
 buildctl:
  Version:      v0.12.5
  GitCommit:    bac3f2b673f3f9d33e79046008e7a38e856b3dc6

Server:
 containerd:
  Version:      v1.7.16
  GitCommit:    83031836b2cf55637d7abf847b17134c51b38e53
 runc:
  Version:      1.1.12
  GitCommit:    v1.1.12-0-g51d5e946
```

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

```
Client:
 Namespace:     default
 Debug Mode:    false

Server:
 Server Version: v1.7.16
 Storage Driver: overlayfs
 Logging Driver: json-file
  Cgroup Driver:  : systemd
  Cgroup Version: : 2
 Plugins:
  Log:     fluentd journald json-file syslog
  Storage: native overlayfs
 Security Options:
  apparmor
  seccomp
   Profile:     builtin
  cgroupns
 Kernel Version:   6.8.0-39-generic
 Operating System: Ubuntu 24.04 LTS
 OSType:           linux
 Architecture:     aarch64
 CPUs:             9
 Total Memory:     9.69GiB
 Name:             colima-devenv
 ID:               1c2a14b0-6d79-418c-a142-9e9584061fc3
```

**Comment by apostasie** [comment] 2024-10-01 17:20
Duplicate of #3006

**Closed** 2024-10-02 02:29 UTC
Labels: duplicate
