### ISSUE TITLE
[v0.16.0, Harbor] nerdctl login on private registry is using port 8443

### ISSUE THREAD

**Issue by rrey** [containerd/nerdctl#773] opened 2022-02-01 15:06 UTC
```
nerdctl --version
nerdctl version 0.16.0
```

I have a private registry (harbor) that is reachable on port 443, but when I try to login with nerctl, it seems like it tries to reach it on port 8443:

```
$ nerdctl login <some_public_registry_listeining_on_443> -u username --debug
Enter Password:
DEBU[0001] Ignoring hosts dir "/etc/containerd/certs.d"  error="stat /etc/containerd/certs.d: no such file or directory"
DEBU[0001] Ignoring hosts dir "/etc/docker/certs.d"      error="stat /etc/docker/certs.d: no such file or directory"
DEBU[0001] len(regHosts)=1
ERRO[0001] failed to call tryLoginWithRegHost            error="failed to call rh.Client.Do: Get \"https://<some_public_registry_listeining_on_443>:8443/v2/\": dial tcp <some_ip>:8443: connect: connection refused" i=0
FATA[0001] failed to call rh.Client.Do: Get "https://<some_public_registry_listeining_on_443>:8443/v2/": dial tcp <some_ip>:8443: connect: connection refused
```

Even if I provide `address:port` (`<some_public_registry_listeining_on_443>:443`), the logs shows that port 8443 is still used.

**Comment by rrey** [comment] 2022-02-01 20:07
Noob question, how can I pull this version on macOS ? 
I’m a total stranger with lima and stuff

**Comment by AkihiroSuda** [comment] 2022-02-02 05:51
Please install lima v0.8.2 (`brew upgrade`) and recreate the instance (`limactl rm -f default`, `limactl start`).

If you prefer to retain the existing instance, just replace `/usr/local/bin/nerdctl` in the instance with `nerdctl` included in `nerdctl-<VERSION>-linux-<ARCH>.tar.gz`
https://github.com/containerd/nerdctl/releases/download/v0.16.1/nerdctl-0.16.1-linux-amd64.tar.gz (Intel)
https://github.com/containerd/nerdctl/releases/download/v0.16.1/nerdctl-0.16.1-linux-arm64.tar.gz (ARM)

**Comment by gregorso** [comment] 2022-02-04 19:46
Hi there. I've a similar problem. If i use nerdctl run   --publish 443:443  the https works well. If i'm using compose https is not reachable. 
nerdctl version 0.16.1   with containerd on centos 8

**Comment by Junnplus** [comment] 2022-02-10 15:50
@rrey I think the harbor problem may be related to the configuration of your harbor server. `external_url` may be configured with an address of 8443.

**Comment by rrey** [comment] 2022-02-10 16:26
@Junnplus I check the config and the `external_url` was not set, setting it do not fix the problem.
docker client has no problem performing the login so I don't think it is a harbor problem. We also use the registry with a live K8S cluster with an imagePullSecret and it is working properly.

I did not have time to check the nerdctl v0.16.1 yet.

**Comment by Junnplus** [comment] 2022-02-10 17:00
> I check the config and the external_url was not set, setting it do not fix the problem.

I can't think of anywhere else that would cause the port to change if `external_url` is not set. I can't reproduce this problem locally.

**Comment by rrey** [comment] 2022-02-10 20:14
Updated to 016.1:
```
$ nerdctl --version
nerdctl version 0.16.1
```

`nerdctl login` do not fail anymore but the pull fails with following error:
```
FATA[0000] failed to resolve reference "<registry>/<image>/<path>:<tag>": pulling from host <registry> failed with status code [manifests <tag>]: 401 Unauthorized
`
``

Testing with docker desktop with same image and credentials works like a charm.

**Comment by Junnplus** [comment] 2022-02-11 02:31
> nerdctl login do not fail anymore but the pull fails with following error

You need to check the `/root/.docker/config.json` file, may be related to https://github.com/containerd/nerdctl/pull/783

**Comment by junnplus** [comment] 2022-05-01 07:28
I closed it, feel free to reopen it if you still have problems.

**Closed by junnplus** 2022-05-01 07:28 UTC
Labels: bug
